apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node
spec:
  replicas: 2  # Change this to scale Chrome instances
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: selenium/node-chrome:latest
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4442"
            - name: SE_EVENT_BUS_PORT
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "5"
            - name: NODE_MAX_SESSION
              value: "5"
