apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-node
spec:
  replicas: 2  # Change this to scale Firefox instances
  selector:
    matchLabels:
      app: firefox-node
  template:
    metadata:
      labels:
        app: firefox-node
    spec:
      containers:
        - name: firefox-node
          image: selenium/node-firefox:latest
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PORT
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "5"
            - name: NODE_MAX_SESSION
              value: "5"
