apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-node
  labels:
    app: firefox-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefox-node
  template:
    metadata:
      labels:
        app: firefox-node
    spec:
      containers:
        - name: firefox-node
          image: selenium/node-firefox:latest
          ports:
            - containerPort: 5555
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT  # Add this to set the publish port
              value: "4442"  # Set an unused port for the node to publish to
            - name: NODE_MAX_INSTANCES
              value: "5"
            - name: NODE_MAX_SESSION
              value: "5"
