apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web-ui
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30000 # Optional: Expose externally
    - name: event-bus-pub
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: event-bus-sub
      protocol: TCP
      port: 4443
      targetPort: 4443
  type: NodePort