apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web-ui
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30000 # Optional: Expose externally
    - name: event-bus-pub
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: event-bus-sub
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: event-bus-5555  # Add new port for 5555
      protocol: TCP
      port: 5555
      targetPort: 5555
  type: NodePort
