apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web-ui
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30444
    - name: event-bus-pub
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: event-bus-sub
      protocol: TCP
      port: 4443
      targetPort: 4443
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:latest
          ports:
            - containerPort: 4444
            - containerPort: 4442
            - containerPort: 4443
          env:
            - name: GRID_MAX_SESSION
              value: "10"  # Set the maximum number of parallel sessions here
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_PORT
              value: "4444"
